files = Split("""
    hell.cpp 
    common.cpp 
    pretreator/UserIDTransfer.cpp 
    pretreator/TrainSetLoader.cpp 
    pretreator/ProbeLoader.cpp 
    pretreator/QualiSetLoader.cpp
    model/Model.cpp
    model/Bias.cpp 
    model/Implicit.cpp 
    model/SVD.cpp 
""")
Program("hell", files)
